apiVersion: v1
kind: Secret
metadata:
  name: monitor-secret
  namespace: monitoring
type: Opaque
stringData:
  MYSQL_PASSWORD: "123456"
  URL: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxx"
  API_KEY: "sk-xxx"
  API_URL: "https://api.deepseek.com/v1"   # 可选
  MODEL_NAME: "deepseek-reasoner"          # 可选
