apiVersion: v1
kind: Service
metadata:
  name: node-monitor
  namespace: monitoring
  labels:
    app: node-monitor
spec:
  selector:
    app: node-monitor
  ports:
  - port: 8000
    name: metrics
    targetPort: 8000
  clusterIP: None
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
